modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "paleworldfx"
displayName = "Pale World FX"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "VesMaybeVesper"
description = '''A VFX mod focused on the Pale Garden!'''

[[mixins]]
config = "paleworldfx.mixins.json"

[[dependencies.paleworldfx]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.paleworldfx]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
