modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "palegardenfx"
displayName = "Pale Garden FX"
version = "${version}"
displayURL = ""
logoFile = "assets/icon.png"
authors = "VesMaybeVesper"
description = '''A VFX mod focused on the Pale Garden!'''

[[mixins]]
config = "palegardenfx.mixins.json"

[[dependencies.palegardenfx]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.palegardenfx]]
modId = "minecraft"
type = "required"

[[dependancies.palegardenfx]]
modId= "eveningstarlib"
type = "required"
versionRange = "[1.2.0,)"
